model:
  unet:
    pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1
    input_perturbation: 0.0
    revision: null
    resolution: 256
    use_ema: false
    noise_offset: 0.0
    prediction_type: epsilon
    unet_down_blocks:
      - CrossAttnDownBlock2DHalfGated
      - CrossAttnDownBlock2DHalfGated
      - CrossAttnDownBlock2DHalfGated
      - DownBlock2DHalfGated

    unet_mid_block: UNetMidBlock2DCrossAttnWidthGated
      
    unet_up_blocks:
      - UpBlock2DHalfGated
      - CrossAttnUpBlock2DHalfGated
      - CrossAttnUpBlock2DHalfGated
      - CrossAttnUpBlock2DHalfGated

    gated_ff: true
    ff_gate_width: 32

  hypernet:
    weight_norm: false
    linear_bias: true

  quantizer:
    quantizer_T: 0.4
    quantizer_base: 0.1
    num_arch_vq_codebook_embeddings: 16
    arch_vq_beta: 0.25
    depth_order: [-1, -2, 0, 1, -3, -4, 2, 3, -5, -6, 4, 5, -7, 6]
    non_zero_width: true


data:
  dataset_name: null
  data_files: null
  dataset_config_name: null
  data_dir: "/fs/vulcan-datasets/conceptual_captions"

  train_data_dir: "training"
  train_data_file: "Train_GCC-training.tsv"
  train_bad_images_path: "/fs/cbcb-scratch/aliganj/projects/dp_final/diffusion_pruning/data/train_cc3m_bad_images.txt"
  max_train_samples: 100000

  validation_data_dir: "validation"
  validation_data_file: "Validation_GCC-1.1.0-Validation.tsv"
  validation_bad_images_path: "/fs/cbcb-scratch/aliganj/projects/dp_final/diffusion_pruning/data/validation_cc3m_bad_images.txt"
  max_validation_samples: null

  image_column: "image"
  caption_column: "caption"
  prompts: null
  max_generated_samples: 32
  dataloader:
    dataloader_num_workers: 0
    train_batch_size: 32
    validation_batch_size: 4
    center_crop: false
    random_flip: true


training:
  num_train_epochs: 15
  max_train_steps: null
  validation_steps: 100
  image_logging_steps: 100
  mixed_precision: null
  gradient_accumulation_steps: 1
  gradient_checkpointing: false
  local_rank: -1
  num_inference_steps: 100
  allow_tf32: false
  enable_xformers_memory_efficient_attention: false

  losses:
    diffusion_loss:
      snr_gamma: null

    resource_loss:
      type: log
      weight: 1.0
      pruning_target: 0.8

    quantization_loss:
      weight: 1.0

    contrastive_clip_loss:
      arch_vector_temperature: 0.05
      prompt_embedding_temperature: 0.15
      weight: 0.2

  optim:
    hypernet_learning_rate: 0.001
    quantizer_learning_rate: 0.001
    quantizer_weight_decay: 0.01
    hypernet_weight_decay: 0.01
    scale_lr: false
    lr_scheduler: "constant"
    lr_warmup_steps: 200
    use_8bit_adam: false
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_epsilon: 1e-08
    max_grad_norm: 1.0

  hf_hub:
    push_to_hub: false
    hub_token: null
    hub_model_id: null

  logging:
    logging_dir: "/fs/cbcb-scratch/aliganj/results"
    report_to: "wandb"
    checkpoints_total_limit: 1
    resume_from_checkpoint: "latest"
    tracker_project_name: "text2image-dynamic-pruning"

